# Generated by Django 4.2.5 on 2023-09-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=24),
        ),
    ]
